version: '3'
services:
    ark-server:
        container_name: arktemp
        image: turzam/ark
        ports:
            - "7778:7778"
            - "7778:7778/udp"
            - "7777:7777"
            - "7777:7777/udp"
            - "27015:27015"
            - "27015:27015/udp"
        tty: true
        stdin_open: true
        restart: always
        volumes:
            - ./ark:/ark
        env_file:
            - ./.env
        command:
            - 'env'